#!/bin/sh
set -euf -o pipefail

if [[ ! -e /run/etc/.inited ]]; then
  ( cd /etc/etc-skel; cp -a . /run/etc )
  mkdir -m 700 -p /run/etc/ssh
  /usr/bin/ssh-keygen -t ed25519 -N '' -f /run/etc/ssh/ssh_host_ed25519_key
  touch /run/etc/.inited
fi

if [[ -x /run/backdoor-setup ]]; then
  /run/backdoor-setup || true
fi

exec /usr/sbin/sshd -D \
  -E /proc/self/fd/2 \
  -f /dev/null \
  -h /run/etc/ssh/ssh_host_ed25519_key \
  -o PasswordAuthentication=no \
  -o PermitRootLogin=no \
  -o AllowAgentForwarding=no \
  -o AllowTcpForwarding=no
