# This docker-compose file is only for building the custom images defined in
# this repository.  (This might be more suitable for a separate tool, but the
# build needs are simple and we are already using docker-compose, so...)
services:

  mailman2:
    image: davismakerspace.org/mailman2:${TAG}
    build:
      context: mailman2
      args:
        major_minor_version: 2.1
        patch_version: 39
        keys: C638CAEF0AC21563736B5A22555B975E953B8693

  opensmtpd:
    image: davismakerspace.org/opensmtpd:${TAG}
    build: opensmtpd

  gitit:
    image: davismakerspace.org/gitit:${TAG}
    build: gitit

  dkimproxy:
    image: davismakerspace.org/dkimproxy:${TAG}
    build: dkimproxy

  dkimkeys:
    image: davismakerspace.org/dkimkeys:${TAG}
    build: dkimkeys

  certbot:
    image: davismakerspace.org/certbot:${TAG}
    build: certbot

  php-fpm:
    image: davismakerspace.org/php-fpm:${TAG}
    build:
      context: php-fpm
      args:
        version: 7.4

  # Use MariaDB in Alpine Linux to save space;
  # no Alpine version exists in https://hub.docker.com/_/mariadb/
  mariadb:
    image: davismakerspace.org/mariadb:${TAG}
    build: mariadb
