#!/bin/sh
set -euf -o pipefail

version=${major_minor_version}.${patch_version}
url=https://launchpad.net/mailman/${major_minor_version}/${version}/+download/mailman-${version}.tgz

build_pkgs="curl gnupg make gcc libc-dev python2-dev"
data_dirs="archives data lists locks logs qfiles spam"

apk --no-cache add $build_pkgs

# Get environment ready for Mailman
base=/usr/local/mailman
mkdir -p "$base/.skel"
chown mailman:mailman "$base"
chmod a+rx,g+ws "$base"

# Download, verify, and install Mailman
curl -L -O ${url} -O ${url}.asc
gpg --keyserver keyserver.ubuntu.com --recv-keys ${keys}
gpg --verify mailman-${version}.tgz.asc mailman-${version}.tgz
su mailman sh -c "set -euf -o pipefail
  cd /tmp
  tar -xf /mailman-${version}.tgz
  cd mailman-${version}
  patch bin/mailmanctl /mailmanctl.patch
  ./configure \
    --with-mail-gid=smtpd \
    --with-cgi-gid=apache
  make install
"
crontab -u mailman /usr/local/mailman/cron/crontab.in

# Create skeleton mutable data directories, and link the mutable data
# directories to an expected volume mount at /run/mailman.
for d in $data_dirs; do
  mv "$base/$d" "$base/.skel/"
  ln -s "/run/mailman/$d" "$base/$d"
done

# Cleanup
rm -rf \
  "$0" \
  /mailman-${version}.tgz.asc \
  /mailman-${version}.tgz \
  /tmp/mailman-${version} \
  /mailmanctl.patch \
  /etc/smtpd
apk --no-cache del $build_pkgs
