from Defaults import *

DEFAULT_EMAIL_HOST = 'lists.davismakerspace.org'
DEFAULT_URL_HOST = 'lists.davismakerspace.org'
add_virtualhost(DEFAULT_URL_HOST, DEFAULT_EMAIL_HOST)
DEFAULT_URL_PATTERN = 'https://%s/'

# We're actually using OpenSMTPD, but we can use the autogenerated aliases file.
MTA = 'Postfix'
POSTFIX_ALIAS_CMD = '/usr/sbin/makemap -t aliases'

SMTPHOST = 'mailman2-opensmtpd'
